# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

native_cpp_obj_fun_ <- function(name, y_vec, x_mat, b_vec, r_eff) {
    .Call('_ncpen_native_cpp_obj_fun_', PACKAGE = 'ncpen', name, y_vec, x_mat, b_vec, r_eff)
}

native_cpp_obj_grad_fun_ <- function(name, y_vec, x_mat, b_vec, r_eff) {
    .Call('_ncpen_native_cpp_obj_grad_fun_', PACKAGE = 'ncpen', name, y_vec, x_mat, b_vec, r_eff)
}

native_cpp_qlasso_fun_ <- function(q_mat, l_vec, b_vec0, w_vec, lam, iter_max, b_eps, k_eps, p_eff, q_rank) {
    .Call('_ncpen_native_cpp_qlasso_fun_', PACKAGE = 'ncpen', q_mat, l_vec, b_vec0, w_vec, lam, iter_max, b_eps, k_eps, p_eff, q_rank)
}

native_cpp_p_ncpen_fun_ <- function(y_vec, x_mat, b_vec, w_vec, lam, gam, tau, iter_max, b_eps, k_eps, p_eff, r_eff, family, penalty) {
    .Call('_ncpen_native_cpp_p_ncpen_fun_', PACKAGE = 'ncpen', y_vec, x_mat, b_vec, w_vec, lam, gam, tau, iter_max, b_eps, k_eps, p_eff, r_eff, family, penalty)
}

native_cpp_ncpen_fun_ <- function(y_vec, x_mat0, x_std, intc, w_vec0, lam_vec0, r_lam, gam, tau, p_max, iter_max, b_eps, k_eps, p_eff, r_eff, family, penalty) {
    .Call('_ncpen_native_cpp_ncpen_fun_', PACKAGE = 'ncpen', y_vec, x_mat0, x_std, intc, w_vec0, lam_vec0, r_lam, gam, tau, p_max, iter_max, b_eps, k_eps, p_eff, r_eff, family, penalty)
}

