# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' Native object function.
#'
#' @description
#' This is internal use only function. Manual left blank on purpose.
#'
#' @param name .
#' @param y_vec .
#' @param x_mat .
#' @param b_vec .
#'
#'
#' @return
#' .
#'
native_cpp_obj_fun_ <- function(name, y_vec, x_mat, b_vec) {
    .Call(`_ncpen_native_cpp_obj_fun_`, name, y_vec, x_mat, b_vec)
}

#' @title
#' Native object gradient function.
#'
#' @description
#' This is internal use only function. Manual left blank on purpose.
#'
#' @param name .
#' @param y_vec .
#' @param x_mat .
#' @param b_vec .
#'
#'
#' @return
#' .
#'
native_cpp_obj_grad_fun_ <- function(name, y_vec, x_mat, b_vec) {
    .Call(`_ncpen_native_cpp_obj_grad_fun_`, name, y_vec, x_mat, b_vec)
}

#' @title
#' Native object Hessian function.
#'
#' @description
#' This is internal use only function. Manual left blank on purpose.
#'
#' @param name .
#' @param y_vec .
#' @param x_mat .
#' @param b_vec .
#'
#'
#' @return
#' .
#'
native_cpp_obj_hess_fun_ <- function(name, y_vec, x_mat, b_vec) {
    .Call(`_ncpen_native_cpp_obj_hess_fun_`, name, y_vec, x_mat, b_vec)
}

#' @title
#' Native QLASSO function.
#'
#' @description
#' This is internal use only function. Manual left blank on purpose.
#'
#' @param q_mat .
#' @param l_vec .
#' @param b_vec0 .
#' @param w_vec .
#' @param lam .
#' @param iter_max .
#' @param b_eps .
#' @param k_eps .
#' @param p_eff .
#' @param q_rank .
#'
#' @return
#' .
#'
native_cpp_qlasso_fun_ <- function(q_mat, l_vec, b_vec0, w_vec, lam, iter_max, b_eps, k_eps, p_eff, q_rank) {
    .Call(`_ncpen_native_cpp_qlasso_fun_`, q_mat, l_vec, b_vec0, w_vec, lam, iter_max, b_eps, k_eps, p_eff, q_rank)
}

#' @title
#' Native point ncpen function.
#'
#' @description
#' This is internal use only function. Manual left blank on purpose.
#'
#' @param y_vec .
#' @param x_mat .
#' @param b_vec .
#' @param w_vec .
#' @param lam .
#' @param gam .
#' @param tau .
#' @param alp .
#' @param iter_max .
#' @param b_eps .
#' @param k_eps .
#' @param p_eff .
#' @param family .
#' @param penalty .
#'
#' @return
#' .
#'
native_cpp_p_ncpen_fun_ <- function(y_vec, x_mat, b_vec, w_vec, lam, gam, tau, alp, iter_max, b_eps, k_eps, p_eff, family, penalty) {
    .Call(`_ncpen_native_cpp_p_ncpen_fun_`, y_vec, x_mat, b_vec, w_vec, lam, gam, tau, alp, iter_max, b_eps, k_eps, p_eff, family, penalty)
}

#' @title
#' Native ncpen function.
#'
#' @description
#' This is internal use only function. Manual left blank on purpose.
#'
#' @param y_vec .
#' @param x_mat0 .
#' @param w_vec0 .
#' @param lam_vec0 .
#' @param gam .
#' @param tau .
#' @param alp .
#' @param d_max .
#' @param iter_max .
#' @param b_eps .
#' @param k_eps .
#' @param p_eff .
#' @param family .
#' @param penalty .
#' @param loc .
#' @param ob_vec .
#' @param div .
#'
#' @return
#' .
#'
native_cpp_ncpen_fun_ <- function(y_vec, x_mat0, w_vec0, lam_vec0, gam, tau, alp, d_max, iter_max, b_eps, k_eps, p_eff, family, penalty, loc, ob_vec, div) {
    .Call(`_ncpen_native_cpp_ncpen_fun_`, y_vec, x_mat0, w_vec0, lam_vec0, gam, tau, alp, d_max, iter_max, b_eps, k_eps, p_eff, family, penalty, loc, ob_vec, div)
}

